#decred-golang-builder-1.11
# This image may be called with the run_tests.sh script included in any of the
# supported go repos.
# ./run_tests.sh 1.11

FROM golang:1.11.9

LABEL description="Decred golang builder image"
LABEL version="1.1"
LABEL maintainer "dhill@mindcry.org"

ENV TERM linux
ENV USER build

# create user
RUN adduser --disabled-password --gecos ''  $USER

# update base distro & install build tooling
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -qy rsync git xz-utils

# create directory for build artifacts, adjust user permissions
RUN mkdir /release && \
    chown $USER /release

# create directory to get source from
RUN mkdir /src && \
    chown $USER /src && \
    mkdir -p /go/src/github.com/decred && \
    chown -R $USER /go/src

# switch user
USER $USER
ENV HOME /home/$USER

# get linters
ENV GOLANGCI_TAG v1.16.0

WORKDIR /go/src
    RUN git clone --branch $GOLANGCI_TAG https://github.com/golangci/golangci-lint && \
    cd golangci-lint/cmd/golangci-lint && \
    GO111MODULE=on go install
