#decrediton-builder
# This image should be called from the script build-docker.sh in the
# decred/decrediton repo.
# ./build-docker.sh

FROM node:8.9.4

LABEL description="Decrediton builder image"
LABEL version="1.2"
LABEL maintainer "john@netpurgatory.com"

USER build
WORKDIR /home/$USER

COPY ./ /home/$USER

RUN yarn install

CMD yarn run package-linux
