#DOCKER_IMAGE_TAG=dcrd-testnet-insight
#mkdir .dcrd
#docker run -d --network=host -P -v $(pwd)/.dcrd/:/home/decred/.dcrd/ decred/$DOCKER_IMAGE_TAG

FROM decred/dcrd-mainnet

LABEL description="Decred testnet daemon (insight options)"
LABEL version="1.0"
LABEL maintainer "john@netpurgatory.com"

CMD ./dcrd --testnet -u user -P pass --notls --txindex --listen=127.0.0.1
